name = "personal_site-worker"
type = "javascript"
account_id = "your account id"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
compatibility_date = "2022-04-09"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"